# Site settings
# These are used to personalize your new site.
title: Jacob Davies # your name here
logo: "/images/IMG_1238 (3).JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2022)
  <br /><br />
  <a href="https://example.com/resume">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
repository: "jacobdavies/jacobdavies.github.io"
github_username:  jacobdavies # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

